repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/crate-ci/typos
    rev: v1.17.2
    hooks:
      - id: typos


  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
        additional_dependencies: [jupytext]  # optional, only if you're using Jupytext
        args: ["--nbqa-shell"]

  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.11'  # or any later Vulture version
    hooks:
      - id: vulture

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.7' # Update me!
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
