repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: flake8

repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.13.6
    hooks:
      - id: typos-src
