- id: vulture
  name: vulture
  language: python
  entry: vulture
  description: Find unused Python code.
  types: [python]
  pass_filenames: false
  require_serial: true

- id: pydocstyle
  name: pydocstyle
  description: pydocstyle is a static analysis tool for checking compliance with Python docstring conventions.
  entry: pydocstyle
  language: python
  types: [python]
