isort:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install isort
      run: |
        python -m pip install isort

    - name: Run isort
      run: |
        isort --check .
